services:
  app:
    build:
      context: .
    ports:
      - 3000:80
    volumes:
      - .:/rails
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
      POSTGRES_HOST: postgres
  solid_queue:
    build:
      context: .
    command: "bundle exec rails solid_queue:start"
    volumes:
      - .:/rails
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
      JOB_CONCURRENCY: 4
      POSTGRES_HOST: postgres
  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq
    volumes:
      - .:/rails
    depends_on:
      - redis
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
  redis:
    image: redis:latest
    environment:
      TZ: Asia/Tokyo
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
volumes:
  db-data:
    driver: local
