services:
  app:
    build:
      context: .
    ports:
      - 3000:80
    volumes:
      - .:/rails
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
  worker:
    build:
      context: .
    command: bundle exec sidekiq
    volumes:
      - .:/rails
    depends_on:
      - redis
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
      RAILS_MAX_THREADS: 10
  redis:
    image: redis:latest
    environment:
      TZ: Asia/Tokyo
