# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSGTRES_PASSWORD", "password") %>


development:
  primary: &primary_development
    <<: *default
    database: sidekiq_memory_test_development
  cache:
    <<: *primary_development
    database: sidekiq_memory_test_development_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_development
    database: sidekiq_memory_test_development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_development
    database: sidekiq_memory_test_development_cable
    migrations_paths: db/cable_migrate

test:
  primary: &primary_test
    <<: *default
    database: sidekiq_memory_test_test
  cache:
    <<: *primary_test
    database: sidekiq_memory_test_test_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_test
    database: sidekiq_memory_test_test_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_test
    database: sidekiq_memory_test_test_cable
    migrations_paths: db/cable_migrate

production:
  primary: &primary_production
    <<: *default
    database: sidekiq_memory_test_production
  cache:
    <<: *primary_production
    database: sidekiq_memory_test_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: sidekiq_memory_test_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: sidekiq_memory_test_production_cable
    migrations_paths: db/cable_migrate
